### PR TITLE
Mavenize LungJ

### PR DESCRIPTION
**Pull request by imagejan**
I converted your project into a Maven project.

* [x] removed binary files from git, they should not be in the repo at all
* [x] moved java files into `src/main/java`
* [x] moved plugins.config into `src/main/resources`
* [x] replaced broken characters due to wrong encoding
* [x] added a `pom.xml` to manage the dependencies

My eclipse also replaced all line endings. To see the diffs ignoring the whitespace changes, add `?w=1` to the URL in the browser: https://github.com/LWollatz/LungJ/pull/1/files?w=1

To work with this project in eclipse, just *File > Import > Maven > Existing Maven Projects...*.

You might still want to:

* [ ] adapt developer instructions in the readme ("to install, run `mvn`")
* [ ] upload a jar file for users separately from git, creating a GitHub release tag

### CODE REVIEW

**Review by LWollatz — COMMENTED** [review]
Thanks for that! Will the changes be automatically compatible with my current set up of Eclipse, or will I need to change anything?

**Comment by LWollatz** [comment]
ups, that backfired :-D
I thought the problem was modification of files from my side on top of the movement from your side...

**Comment by LWollatz** [comment]
@imagejan: Will change the instructions once I get Maven to run myself. Still complaining about a missing compiler though I checked the JDK everywhere as advised online and Ants works without any problems...
The release tag is already drafted actually, just waiting to link it to the right commit. :-)

**Comment by imagejan** [comment]
> Still complaining about a missing compiler

By any chance, does your `JAVA_HOME` environment variable point to a JRE instead of a JDK? What's the exact error message?

**Comment by LWollatz** [comment]
I am trying to figure that out. But it tells me 
LungJ_ [Maven Build] C:\Users...\win64\jdk1.6.0_24\jre\bin\javaw.exe
...

> [INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ LungJ ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 33 source files to \...\Eclipse\LungJ_\target\classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> [ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
> [INFO] 1 error

I will see that I remove any JREs I can find (there actually is a jre 1.8 in the same directory as the jdk 1.6) but so far that never caused me any problems :-/
Also found some more online forum solutions to try :-)
Maybe I am too stubborn, trying to get Maven to run as neatly as Ant did - fully integrated in Eclipse and automatic building as soon as I save changes...

**Comment by imagejan** [comment]
What's the content of your `JAVA_HOME`?

`echo %JAVA_HOME%`

**Comment by LWollatz** [comment]
Sorry, but I have no idea where to execute that (in Eclipse I presume)

I did manage to build using Maven, once I completely removed the jre 1.8 from Eclipse only that it complains that it can't execute EclipseHelper's main() method (I don't have a main() method, so I think that's ok)
The resulting Plug-In does create Menu Entries in Fiji, but is not able to link them to the code. Will see that I work myself through this tomorrow. At least I think it builds on save again. :-)

**Comment by LWollatz** [comment]
@imagejan Did a clean new project on Eclipse, pulling from GitHub with Maven. It now creates a jar and that works. It still has a build failure, but that lies now with 

> Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project LungJ: Compilation failure
> Could not execute EclipseHelper's main() method (org.scijava:scijava-maven-plugin:0.5.1:eclipse-helper:default:process-classes)

As it produces a jar file that seems to work with my local Fiji, I will just leave it untouched from now on unless you have any more advise... :-)

Thanks again for your help!

**Comment by imagejan** [comment]
> > echo %JAVA_HOME%
> 
> Sorry, but I have no idea where to execute that (in Eclipse I presume)

Oh, sorry, that was meant for running Maven from the command prompt.

In Eclipse, the version of JDK or JRE you're running is configured in your `eclipse.ini` file:

```
-vm
C:\Program Files\Java\jdk1.8.0_102\bin\javaw.exe
```

> Could not execute EclipseHelper's main() method (org.scijava:scijava-maven-plugin:0.5.1:eclipse-helper:default:process-classes)

Hm, as I'm neither a Maven expert nor an Eclipse expert, I don't know how to fix this.
Do you see the same error when building from the command line, using simply `mvn` ?

You can also post this on the [forum](http://forum.imagej.net/), maybe @ctrueden or others can help you here.

**Comment by LWollatz** [comment]
I seemed to have fixed it. I went through all my different Java JREs and JDKs and placed them neatly in one folder and made sure all Eclipse links only go to that folder. (eclipse.ini and any GUI general and project specific settings) Then I found that maven was trying to compile the javadoc with a JRE rather than a JDK changed that, compiled everything with _JDK 1.8_ rather than _JDK 1.8/ Java 6 compatibility mode_ and it worked all fine. 
I don't know if it does any of the Maven repository uploading correctly but no errors show up and with Java 8 in my Fiji directory I can run the plug-in just fine :-)

**Pull request merged**
